import type { PrebuiltScenario } from '../../shared/src/types.js';

// All four scenarios use the New York ARTCC area (~lat 40-42, lon -72 to -76).
// Aircraft positions are chosen so conflicts develop 4–8 minutes after start,
// giving the controller enough time to react while still feeling urgent.

export const SCENARIOS: PrebuiltScenario[] = [
  {
    id: 'scenario-1',
    name: 'Head-On Conflict',
    description: 'Two aircraft flying directly at each other at the same altitude.',
    difficulty: 'easy',
    duration: 600,
    centerLat: 40.70,
    centerLon: -74.00,
    radarRange: 130,
    objectives: [
      'Identify the converging conflict between AAL100 and UAL200',
      'Issue a heading OR altitude change to one aircraft',
      'Restore 5 nm horizontal OR 1 000 ft vertical separation',
    ],
    aircraft: [
      {
        id: 'ac-aal100',
        callsign: 'AAL100',
        latitude: 40.70,
        longitude: -75.20,
        altitude: 25000,
        heading: 90,
        speed: 450,
        timestamp: 0,
      },
      {
        id: 'ac-ual200',
        callsign: 'UAL200',
        latitude: 40.70,
        longitude: -72.80,
        altitude: 25000,
        heading: 270,
        speed: 420,
        timestamp: 0,
      },
    ],
  },

  {
    id: 'scenario-2',
    name: 'Crossing Paths',
    description: 'Two aircraft on intersecting tracks will meet at a common point.',
    difficulty: 'medium',
    duration: 720,
    centerLat: 41.10,
    centerLon: -74.20,
    radarRange: 140,
    objectives: [
      'Determine which aircraft reaches the crossing point first',
      'Issue heading, altitude, or speed instructions to resolve',
      'Act before the 10-minute window closes',
    ],
    aircraft: [
      {
        id: 'ac-dal300',
        callsign: 'DAL300',
        latitude: 40.70,
        longitude: -75.20,
        altitude: 28000,
        heading: 60,
        speed: 420,
        timestamp: 0,
      },
      {
        id: 'ac-fdx401',
        callsign: 'FDX401',
        latitude: 42.10,
        longitude: -73.00,
        altitude: 28000,
        heading: 220,
        speed: 390,
        timestamp: 0,
      },
    ],
  },

  {
    id: 'scenario-3',
    name: 'Overtake Conflict',
    description: 'AAL501 is faster and closing on SWA500 along the same route.',
    difficulty: 'medium',
    duration: 600,
    centerLat: 40.70,
    centerLon: -74.75,
    radarRange: 100,
    objectives: [
      'Detect the closing distance on the eastbound route',
      'Speed up SWA500, slow AAL501, or use altitude separation',
      'Maintain 5 nm before the overtake occurs (~7 min)',
    ],
    aircraft: [
      {
        id: 'ac-swa500',
        callsign: 'SWA500',
        latitude: 40.70,
        longitude: -74.50,
        altitude: 35000,
        heading: 90,
        speed: 340,
        timestamp: 0,
      },
      {
        id: 'ac-aal501',
        callsign: 'AAL501',
        latitude: 40.70,
        longitude: -75.00,
        altitude: 35000,
        heading: 90,
        speed: 480,
        timestamp: 0,
      },
    ],
  },

  {
    id: 'scenario-4',
    name: 'Multiple Simultaneous Conflicts',
    description: 'Two independent conflicts require rapid prioritization.',
    difficulty: 'hard',
    duration: 900,
    centerLat: 40.10,
    centerLon: -74.30,
    radarRange: 120,
    objectives: [
      'The SWA/FDX crossing conflict is more urgent (~3 min)',
      'The AAL/UAL head-on conflict follows at ~7 min',
      'Resolve both without creating new conflicts',
    ],
    aircraft: [
      {
        id: 'ac-aal100',
        callsign: 'AAL100',
        latitude: 40.70,
        longitude: -75.20,
        altitude: 25000,
        heading: 90,
        speed: 450,
        timestamp: 0,
      },
      {
        id: 'ac-ual200',
        callsign: 'UAL200',
        latitude: 40.70,
        longitude: -72.80,
        altitude: 25000,
        heading: 270,
        speed: 420,
        timestamp: 0,
      },
      {
        id: 'ac-swa500',
        callsign: 'SWA500',
        latitude: 39.50,
        longitude: -75.00,
        altitude: 28000,
        heading: 0,
        speed: 400,
        timestamp: 0,
      },
      {
        id: 'ac-fdx401',
        callsign: 'FDX401',
        latitude: 39.80,
        longitude: -75.50,
        altitude: 28000,
        heading: 90,
        speed: 380,
        timestamp: 0,
      },
    ],
  },
];
